
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pesbuk-deployment
spec:
  selector:
    matchLabels:
      run: pesbuk-deployment
  replicas: 2
  template:
    metadata:
        labels:
          run: pesbuk-deployment
    spec:
      containers:
        - name: pesbuk-deployment
          image: gandi12/pesbuk:secret
          ports:
            - containerPort: 80
          env:  
            - name: DB_HOST    
              value: devopscilsy.cbbkbjoitxuc.ap-southeast-1.rds.amazonaws.com
            - name: DB_USER    
              valueFrom:       
                secretKeyRef:
                  name: p-secret
                  key: DB_USER  
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: p-secret
                  key: DB_PASS